/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jose Marcos Morales Gomez
 */
public class Vista extends javax.swing.JFrame {
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        DefaultTableModel model1 = new DefaultTableModel();
        model1.addColumn("Nombre");
        model1.addColumn("Ruta");
        model1.addColumn("Fecha");
        this.tableListaOrd.setModel(model1);
        DefaultTableModel model2 = new DefaultTableModel();
        model2.addColumn("Nombre");
        model2.addColumn("Ruta");
        model2.addColumn("Fecha");
        this.tableListaOrd.setModel(model1);
        this.tableArcEnc.setModel(model2);
        
        buttonGroupOrdenamientos.clearSelection();
        buttonGroupOrdenamientos.setSelected(this.btnBurbuja.getModel(), true);
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOrdenamientos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomArchivo = new javax.swing.JTextField();
        nomDirec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBurbuja = new javax.swing.JRadioButton();
        btnInsercion = new javax.swing.JRadioButton();
        btnShell = new javax.swing.JRadioButton();
        btnQuick = new javax.swing.JRadioButton();
        btnMezclaDir = new javax.swing.JRadioButton();
        btnMezclaNat = new javax.swing.JRadioButton();
        btnBusque = new javax.swing.JButton();
        checkSubCarp = new javax.swing.JCheckBox();
        btnSelect = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaOrd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableArcEnc = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Archivo:");

        jLabel2.setText("Directorio:");

        nomArchivo.setText("Estructuras");
        nomArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomArchivoActionPerformed(evt);
            }
        });

        nomDirec.setText("C:\\");

            jLabel3.setText("Tipo de ordenamiento:");

            buttonGroupOrdenamientos.add(btnBurbuja);
            btnBurbuja.setText("Burbuja");

            buttonGroupOrdenamientos.add(btnInsercion);
            btnInsercion.setText("Inserción");
            btnInsercion.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnInsercionActionPerformed(evt);
                }
            });

            buttonGroupOrdenamientos.add(btnShell);
            btnShell.setText("ShellSort");

            buttonGroupOrdenamientos.add(btnQuick);
            btnQuick.setText("QuickSort");
            btnQuick.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnQuickActionPerformed(evt);
                }
            });

            buttonGroupOrdenamientos.add(btnMezclaDir);
            btnMezclaDir.setText("Mezcla directa");
            btnMezclaDir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnMezclaDirActionPerformed(evt);
                }
            });

            buttonGroupOrdenamientos.add(btnMezclaNat);
            btnMezclaNat.setText("Mezcla natural");
            btnMezclaNat.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnMezclaNatActionPerformed(evt);
                }
            });

            btnBusque.setText("Nueva Búsqueda");
            btnBusque.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnBusqueActionPerformed(evt);
                }
            });

            checkSubCarp.setText("Incluir subcarpetas");
            checkSubCarp.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    checkSubCarpActionPerformed(evt);
                }
            });

            btnSelect.setText("Aceptar");
            btnSelect.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSelectActionPerformed(evt);
                }
            });

            jLabel4.setText("Lista ordenado:");

            jLabel5.setText("Archivos encontrados:");

            tableListaOrd.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane1.setViewportView(tableListaOrd);

            tableArcEnc.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            jScrollPane2.setViewportView(tableArcEnc);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nomDirec)
                                        .addComponent(nomArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(checkSubCarp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSelect))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnBusque)
                                    .addGap(54, 54, 54))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBurbuja)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnInsercion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnShell)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnQuick)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnMezclaDir)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMezclaNat))
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(49, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(nomArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBusque))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nomDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkSubCarp)
                        .addComponent(btnSelect))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBurbuja)
                        .addComponent(btnInsercion)
                        .addComponent(btnShell)
                        .addComponent(btnQuick)
                        .addComponent(btnMezclaDir)
                        .addComponent(btnMezclaNat))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void nomArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomArchivoActionPerformed

    private void btnMezclaDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclaDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMezclaDirActionPerformed

    private void btnMezclaNatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclaNatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMezclaNatActionPerformed

    private void btnInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsercionActionPerformed

    private void btnQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuickActionPerformed

    private void btnBusqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusqueActionPerformed

        
    }//GEN-LAST:event_btnBusqueActionPerformed

    private void checkSubCarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSubCarpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSubCarpActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton btnBurbuja;
    public javax.swing.JButton btnBusque;
    public javax.swing.JRadioButton btnInsercion;
    public javax.swing.JRadioButton btnMezclaDir;
    public javax.swing.JRadioButton btnMezclaNat;
    public javax.swing.JRadioButton btnQuick;
    public javax.swing.JButton btnSelect;
    public javax.swing.JRadioButton btnShell;
    private javax.swing.ButtonGroup buttonGroupOrdenamientos;
    public javax.swing.JCheckBox checkSubCarp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField nomArchivo;
    public javax.swing.JTextField nomDirec;
    public javax.swing.JTable tableArcEnc;
    public javax.swing.JTable tableListaOrd;
    // End of variables declaration//GEN-END:variables

    public Object getbuttonGroupOrdenamientos() {
        return buttonGroupOrdenamientos;
    }
}
