
package vista;

import modelo.Archivo;

/**
 *
 * @author Jose Marcos Morales Gomez
 */
public class Vista extends javax.swing.JFrame {
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        votosFresasTextField = new javax.swing.JTextField();
        votosManzanasTextField = new javax.swing.JTextField();
        votosPlatanosTextField = new javax.swing.JTextField();
        fresaButton = new javax.swing.JButton();
        manzanaButton = new javax.swing.JButton();
        platanoButton = new javax.swing.JButton();
        alimentoLabelUno = new javax.swing.JLabel();
        alimentoLabelDos = new javax.swing.JLabel();
        alimentoLabelTres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        votosFresasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votosFresasTextFieldActionPerformed(evt);
            }
        });

        fresaButton.setText("Votar");
        fresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fresaButtonActionPerformed(evt);
            }
        });

        manzanaButton.setText("Votar");

        platanoButton.setText("Votar");
        platanoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platanoButtonActionPerformed(evt);
            }
        });

        alimentoLabelUno.setBackground(new java.awt.Color(51, 51, 51));
        alimentoLabelUno.setText("Fresa");

        alimentoLabelDos.setText("Platano");

        alimentoLabelTres.setText("Manzana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fresaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(votosFresasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manzanaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(votosManzanasTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(platanoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(votosPlatanosTextField))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(alimentoLabelUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alimentoLabelDos)
                .addGap(118, 118, 118)
                .addComponent(alimentoLabelTres)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alimentoLabelUno)
                    .addComponent(alimentoLabelDos)
                    .addComponent(alimentoLabelTres))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fresaButton)
                    .addComponent(manzanaButton)
                    .addComponent(platanoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(votosFresasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(votosManzanasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(votosPlatanosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fresaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fresaButtonActionPerformed

    private void platanoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platanoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platanoButtonActionPerformed

    private void votosFresasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votosFresasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votosFresasTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel alimentoLabelDos;
    public javax.swing.JLabel alimentoLabelTres;
    public javax.swing.JLabel alimentoLabelUno;
    public javax.swing.JButton fresaButton;
    public javax.swing.JButton manzanaButton;
    public javax.swing.JButton platanoButton;
    public javax.swing.JTextField votosFresasTextField;
    public javax.swing.JTextField votosManzanasTextField;
    public javax.swing.JTextField votosPlatanosTextField;
    // End of variables declaration//GEN-END:variables
}
