/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dominio.Vista;

/**
 *
 * @author Jose Marcos Morales Gomez
 */
public class VistaMenuEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuEmpleado
     */
    public VistaMenuEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Menu Empleado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnReserva = new javax.swing.JButton();
        btnLlegada = new javax.swing.JButton();
        btnEstadosHab = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAct = new javax.swing.JButton();
        btnEventos = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("¡Bienvenido Empleado!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 270, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dominio/Vista/LogoHotelELFiel2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, 230));

        btnReserva.setBackground(new java.awt.Color(204, 204, 204));
        btnReserva.setForeground(new java.awt.Color(102, 102, 102));
        btnReserva.setText("Reservar Habitación");
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });
        getContentPane().add(btnReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 190, -1));

        btnLlegada.setBackground(new java.awt.Color(204, 204, 204));
        btnLlegada.setForeground(new java.awt.Color(102, 102, 102));
        btnLlegada.setText("Reportar Llegada del Cliente");
        btnLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlegadaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 200, -1));

        btnEstadosHab.setBackground(new java.awt.Color(204, 204, 204));
        btnEstadosHab.setForeground(new java.awt.Color(102, 102, 102));
        btnEstadosHab.setText("Revisar Estado de Cuartos");
        btnEstadosHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosHabActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstadosHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 190, -1));

        btnSalir.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir.setForeground(new java.awt.Color(102, 102, 102));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 78, -1));

        btnAct.setBackground(new java.awt.Color(204, 204, 204));
        btnAct.setForeground(new java.awt.Color(102, 102, 102));
        btnAct.setText("Ver Horario de Actividades");
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });
        getContentPane().add(btnAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 190, -1));

        btnEventos.setBackground(new java.awt.Color(204, 204, 204));
        btnEventos.setForeground(new java.awt.Color(102, 102, 102));
        btnEventos.setText("Ver Horarios de Eventos");
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 190, -1));

        btnAtras.setBackground(new java.awt.Color(204, 204, 204));
        btnAtras.setForeground(new java.awt.Color(102, 102, 102));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dominio/Vista/fondo_degradado.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        VistaReserva ob = new VistaReserva();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlegadaActionPerformed
        VistaLlegada ob = new VistaLlegada();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLlegadaActionPerformed

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
        VistaHorarioEventos ob = new VistaHorarioEventos();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEventosActionPerformed

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
        VistaHorarioAct ob = new VistaHorarioAct();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnActActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VistaRegistro2 ob = new VistaRegistro2();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnEstadosHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosHabActionPerformed
        VistaEstadoDeCuartos ob = new VistaEstadoDeCuartos();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEstadosHabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAct;
    public javax.swing.JButton btnAtras;
    public javax.swing.JButton btnEstadosHab;
    public javax.swing.JButton btnEventos;
    public javax.swing.JButton btnLlegada;
    public javax.swing.JButton btnReserva;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
